version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: side-hustle-app
    working_dir: /var/www
    volumes:
      - ./extracted:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./extracted/storage:/var/www/storage
    environment:
      - PORT=${PORT:-80}
      - APP_ENV=production
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=side_hustle
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    ports:
      - "8000:80"
    networks:
      - side-hustle-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: side-hustle-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: side_hustle
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./side_hustle_DB.sql:/docker-entrypoint-initdb.d/side_hustle_DB.sql
    networks:
      - side-hustle-network

networks:
  side-hustle-network:
    driver: bridge

volumes:
  dbdata: